Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - vendor/bundle/**/*
    - Gemfile

Metrics/LineLength:
  Max: 128

Metrics/AbcSize:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/AsciiComments:
  Enabled: false