Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.5

  Exclude:
    - bin/*
    - config/**/*
    - db/**/*
    - vendor/bundle/**/*
    - Gemfile

Metrics/LineLength:
  Max: 128

MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/AsciiComments:
  Enabled: false